routes/admin.php
<?php 

Route::group(['middleware' => 'web'], function(){



	//Admin
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){
		Route::get('/', function(){ return redirect('/admin/dashboard');});
		Route::get('dashboard', 'DashboardController@dashboard');
		CRUD::resource('usuarios', 'Admin\UsuariosCrudController');
		CRUD::resource('tickets', 'Admin\TicketsCrudController');
		CRUD::resource('categorias', 'Admin\CategoriasCrudController');
		CRUD::resource('files', 'Admin\ArchivosCrudController');

		CRUD::resource('documentos', 'Admin\DocumentoCrudController');
		CRUD::resource('categoriadocumentos', 'Admin\CategoriaDocumentosCrudController');
		Route::get('eliminar-documento/{id}','AdminController@eliminarDocumento');
		Route::get('categorias-masivas/{categoria}', 'AdminController@categoriasUsuarios');
		Route::put('categorias-masivas/{categoria}', 'AdminController@agregarmasivamente');
		Route::get('archivos-masivos/', 'AdminController@archivosMasivos');

		CRUD::resource('alertas', 'Admin\AlertaCrudController');


		Route::get('email/departamento', 'AdminController@emailPorDepartamento');
		Route::get('email/puesto', 'AdminController@emailPorPuesto');
		Route::get('email/usuarios', 'AdminController@emailAUsuarios');
		Route::get('email/usuarios/departamento', 'AdminController@emailAUsuariosPorDepartamento');


		Route::get('crear-atajo', 'AdminController@agregarAccesoRapido');
		Route::get('eliminar-atajo/{id}', 'AdminController@eliminarAccesoRapido');
	});

	//Clinica
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){
		// Historias Clinicas
		CRUD::resource('pacientes', 'Admin\PacienteCrudController');
		CRUD::resource('casos-medicos', 'Admin\Casos_medicosCrudController');
		CRUD::resource('historias_clinicas', 'Admin\HistoriaClinicaCrudController');
		CRUD::resource('recomendaciones', 'Admin\RecomendacionCrudController');
		CRUD::resource('incapacidades', 'Admin\IncapacidadCrudController');
		CRUD::resource('puestos', 'Admin\PuestoCrudController');
		CRUD::resource('fondos-de-pensiones', 'Admin\FondosDePensionesCrudController');
		CRUD::resource('eps', 'Admin\EpsCrudController');
		CRUD::resource('arl', 'Admin\ArlCrudController');
		CRUD::resource('cie10', 'Admin\Cie10CrudController');


		Route::get('ver-paciente/{id}', 'ClinicaController@verPaciente');
		Route::get('ver-caso/{id}', 'ClinicaController@verCasoMedico');
		Route::get('ver-historia-clinica/{id}', 'ClinicaController@verHistoriaClinica');
		Route::get('ver-incapacidad/{id}', 'ClinicaController@verIncapacidad');
		Route::get('iniciar-seguimiento/{id}', 'ClinicaController@iniciarSeguimiento');
		Route::get('paciente/buscar', 'ClinicaController@buscarPaciente');
		
		Route::post('cargar-archivo/paciente/{id}','ClinicaController@cargarArchivoPaciente');
		Route::post('cargar-archivo/caso/{id}','ClinicaController@cargarArchivoCaso');
	});

	//Cientes
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){

		CRUD::resource('clientes', 'Admin\ClienteCrudController');
		CRUD::resource('facturas', 'Admin\InvoiceCrudController');

		CRUD::resource('procesos', 'Admin\ProcesoCrudController');
		CRUD::resource('consultas', 'Admin\ConsultaCrudController');

		Route::get('ver-cliente/{id}', 'ClientesController@verCliente');
		Route::get('ver-proceso/{id}', 'ClientesController@verProceso');
		Route::get('ver-consulta/{id}', 'ClientesController@verConsulta');
		Route::get('ver-invoice/{id}', 'ClientesController@verFactura');
		Route::get('ver-invoice/pdf/{id}', 'ClientesController@verFacturaPdf');

		Route::get('iniciar-seguimiento/proceso/{id}', 'ClientesController@iniciarSeguimientoProceso');
		Route::get('iniciar-seguimiento/consulta/{id}', 'ClientesController@iniciarSeguimientoConsulta');
		
		Route::get('cliente/buscar', 'ClientesController@buscarCliente');

		Route::get('cliente/archivos-masivos','ClientesController@ArchivosMasivosClientes');
		
		Route::post('cargar-archivo/cliente/{id}','ClientesController@cargarArchivoCliente');
		Route::post('cargar-archivo/proceso/{id}','ClientesController@cargarArchivoProceso');
		Route::post('cargar-archivo/consulta/{id}','ClientesController@cargarArchivoConsulta');
		
	});

	// Procesos Masivos
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function() {

		CRUD::resource('procesos-masivos', 'Admin\ProcesoMasivoCrudController');
		CRUD::resource('{proceso_masivo_id}/procesos-masivos-clientes', 'Admin\ProcesosMasivosClienteCrudController');
		CRUD::resource('entidades', 'Admin\EntidadCrudController');
		Route::get('proceso-masivo/archivos-masivos','ProcesoMasivoController@ArchivosMasivosClientes');
		Route::get('ver-procesoMasivo/{id}', 'ProcesoMasivoController@verProceso');
		Route::get('ver-documentos-procesoMasivo/{id}', 'ProcesoMasivoController@verDocumentosProceso');
		Route::get('ver-procesoMasivo/{id}/excel', 'ProcesoMasivoController@verProcesoExcel');
		Route::get('ver-documentos-clientes-procesosMasivos/{id}', 'ProcesoMasivoController@verDocumentosClienteProcesos');
	});

	// Evaluaciones
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){
		CRUD::resource('evaluaciones', 'Admin\EvaluacionCrudController');
		
		CRUD::resource('evaluaciones-proveedores', 'Admin\EvaluacionProveedorCrudController');
		Route::get('ver-evaluacion-proveedor/{evaluacion}', 'AdminController@verEvaluacionProveedor');


		CRUD::resource('vehiculos', 'Admin\VehiculoCrudController');
		CRUD::resource('evaluaciones-vehiculos', 'Admin\EvaluacionVehiculoCrudController');
		Route::get('ver-vehiculo/{vehiculo}', 'AdminController@verVehiculo');
		Route::get('ver-evaluacion-vehiculo/{evaluacion}', 'AdminController@verEvaluacionVehiculo');


		CRUD::resource('conductores', 'Admin\ConductorCrudController');
		CRUD::resource('evaluaciones-conductores', 'Admin\EvaluacionConductorCrudController');
		Route::get('ver-conductor/{conductor}', 'AdminController@verConductor');
		Route::get('ver-evaluacion-conductor/{evaluacion}', 'AdminController@verEvaluacionConductor');

		Route::post('cargar-archivo/proveedor/{id}','UploadController@cargarArchivoProveedor');
		Route::post('cargar-archivo/vehiculo/{id}','UploadController@cargarArchivoVehiculo');
		Route::post('cargar-archivo/conductor/{id}','UploadController@cargarArchivoConductor');

	});

	//Auditoria
	Route::group(['prefix' => 'admin/auditar','middleware' => ['isAdmin']], function(){
		Route::get('usuario/{user_id?}', 'AdminController@auditarUsuario');
		Route::get('resumen', 'AdminController@resumen');	
	});


	//Proveedores
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){
		CRUD::resource('proveedores', 'Admin\ProveedorCrudController');
		CRUD::resource('invoices-proveedores', 'Admin\InvoiceProveedorCrudController');
		
		Route::get('ver-proveedor/{proveedor}', 'ProveedoresController@verProveedor');
		Route::get('ver-invoiceProveedor/{invoice_id}', 'ProveedoresController@verInvoiceProveedor');

	});

	//Pedidos
	Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function(){
		CRUD::resource('productos', 'Admin\ProductoCrudController');
		CRUD::resource('pedidos', 'Admin\PedidoCrudController');
		CRUD::resource('categoriasproductos', 'Admin\CategoriaProductoCrudController');
		
		Route::get('ver-producto/{producto}', 'ProductoController@verProducto');
		Route::get('ver-producto/{producto}/imagenes', 'ProductoController@verProductoImagenes');
		Route::get('ver-pedido/{invoice_id}', 'PedidoController@verPedido');


		Route::post('producto/{producto}/uploadImage', 'ProductoController@uploadImage');
		Route::get('producto/{producto}/image/{image}/default', 'ProductoController@defaultImage');

	});


	


	//Reportes
	Route::group(['prefix' => 'admin/reportes','middleware' => ['isAdmin']], function(){
		Route::get('ticket/{ticket_id?}', 'ReporteController@ticket');
	});

});

routes/web.php
<?php
use Carbon\Carbon;
Jenssegers\Date\Date::setLocale('es');
Carbon::setLocale('es');


Route::auth();
Route::get('logout', 'HomeController@logout');

Route::group(['middleware' => 'web'], function () {

	//Home
	Route::group([], function() {
		Route::get('/', 'HomeController@index');
		Route::get('/home', 'HomeController@home');
		Route::any('/menu',   ['middleware' => [], 'uses' =>'HomeController@menu']);
		Route::any('/calendar',   ['middleware' => ['auth'], 'uses' =>'HomeController@verCalendario']);

		Route::get('profile' ,['middleware' => ['auth'], 'uses' => "HomeController@profile"]);
		Route::put('profile' ,['middleware' => ['auth'], 'uses' => "HomeController@profileUpdate"]);

		Route::any('agregar-ticket', ['middleware' => ['auth'], 'uses' =>'HomeController@ticketAgregar']);
		Route::get('/ticket',   ['middleware' => ['auth'], 'uses' =>'HomeController@tickets']);
		Route::get('/mis-tickets',   ['middleware' => ['auth'], 'uses' =>'HomeController@misTickets']);
		Route::get('/tickets/todos',   ['middleware' => ['auth'], 'uses' =>'HomeController@Todostickets']);
		Route::get('/tickets/categoria/{categoria}',   ['middleware' => ['auth'], 'uses' =>'HomeController@porCategoria']);
		Route::get('/ticket/ver/{id}',   ['middleware' => ['auth'], 'uses' =>'HomeController@ticketVer']);
		Route::get('ticket/eliminar/{id}', ['middleware' => ['auth'], 'uses' =>'HomeController@ticketEliminar']);
		Route::get('ticket/excel/{id}', ['middleware' => ['auth'], 'uses' =>'HomeController@ticketExcel']);
		Route::put('editar-ticket/{id}', ['middleware' => ['auth'], 'uses' => 'HomeController@ticketEditar']);

		Route::get('ver-documentos', ['midleware' => ['auth'], 'uses' => 'HomeController@listarCategorias']);
		Route::get('ver-documentos/{categoria}', ['midleware' => ['auth'], 'uses' => 'HomeController@listarDocumentos']);


		Route::post('agregar-alerta', ['midleware' => ['auth'], 'uses' => 'HomeController@agregarAlerta']);

		Route::get('archivo/{id}',['midleware' => ['auth'], 'uses' => 'HomeController@descargarArchivo']);

		Route::get('getDocumento/{id}', ['middleware' => ['auth'], 'uses' =>'HomeController@getDocumento']);
		Route::get('getEncryptedFile/ticket/{id}/{clave}', ['middleware' => ['auth'], 'uses' =>'HomeController@getFileTicketEncrypted']);
		Route::get('getEncryptedFile/comentario/{id}/{clave}', ['middleware' => ['auth'], 'uses' =>'HomeController@getFileComentarioTicketEncrypted']);

		Route::get('notificaciones/', ['middleware' => ['auth'], 'uses' =>'HomeController@verNotificaciones']);
		Route::get('notificacion/{id}', ['middleware' => ['auth'], 'uses' =>'HomeController@verNotificacion']);
		Route::get('notificaciones/leer-todas', ['middleware' => ['auth'], 'uses' =>'HomeController@NotificacionesLeerTodas']);
		Route::get('notificacion/{id}/leida', ['middleware' => ['auth'], 'uses' =>'HomeController@Leernotificacion']);
		Route::get('notificacion/{id}/noleida', ['middleware' => ['auth'], 'uses' =>'HomeController@NoLeernotificacion']);

		Route::get('crear-atajo', 'AdminController@agregarAccesoRapido');
		Route::get('eliminar-atajo/{id}', 'AdminController@eliminarAccesoRapido');
		Route::get('busqueda',['middleware' => ['auth'], 'uses' => "HomeController@busqueda"]);
	});

	//Miscelaneo
	Route::group(['middleware' =>['auth']], function(){

		Route::get('getListaCategoriasDocumentos', 'AdminController@getListaCategoriasDocumentos');
		Route::get('getListaCategoriasTickets', 'AdminController@getListaCategoriasTickets');
		Route::get('emitir-alerta','AdminController@emitirAlerta');

		Route::get('excel/load', 'UploadController@loadExcel');
		Route::post('excel/load', 'UploadController@seeExcel');
	});


	if(config("modulos.clientes")){
		Route::get('ver-cliente/{id}', 'ClientesController@verCliente');
		Route::get('ver-proceso/{id}', 'ClientesController@verProceso');
		Route::get('ver-consulta/{id}', 'ClientesController@verConsulta');
		Route::get('ver-invoice/{id}', 'ClientesController@verFactura');
		Route::get('clientes-todos', 'ClientesController@ClientesTodos');
	}

	if (config("modulos.proveedores")){
		Route::get('ver-proveedor/{proveedor}', 'ProveedoresController@verProveedor');
		Route::get('ver-invoice-proveedor/{invoice_id}', 'ProveedoresController@verInvoiceProveedor');
	}

	if (config("modulos.procesos_masivos")){
		Route::get('ver-procesoMasivo/{id}', 'ProcesoMasivoController@verProceso');
		Route::get('ver-documentos-procesoMasivo/{id}', 'ProcesoMasivoController@verDocumentosProceso');
		Route::get('ver-documentos-clientes-procesosMasivos/{id}', 'ProcesoMasivoController@verDocumentosClienteProcesos');
		Route::get('add-cliente-to-proceso-masivo','ProcesoMasivoController@addClientetoProceso');
		Route::post('admin/procesos_masivos/cargar-archivo', 'ProcesoMasivoController@CargarArchivosProcesosMasivos');
		Route::post('admin/procesos_masivos/cargar-archivo/{cliente_id}/{proceso_id}', 'ProcesoMasivoController@CargarArchivosProcesosMasivosCliente');
	}

	if (config("modulos.pedidos")) {
		Route::get('ver-producto/{producto}', 'ProductoController@verProducto');
		Route::get('ver-pedido/{pedido}', 'PedidoController@VerPedido');
		Route::get('ver-combo/{combo_id}', 'ProductoController@verCombo');
		Route::get('confirmacion-pedido/{pedido_id}','PedidoController@confirmarPedido');
	}


	// Modulo de Clientes Pedidos
	Route::get("administrar-productos-clientes/{cliente_cod}","AdministracionController@administrarProductos");
	

	// Cargada de Archivos
	Route::post('cargar-archivo', 'AdminController@cargarArchivosMasivos');
	Route::post('admin/clientes/cargar-archivo', 'AdminController@CargarArchivosClientes');
});


Route::get('tickets-procesos-masivos-clientes', 'HomeController@ticketsconclientes');

Route::get('impersonate/{id}','HomeController@impersonate');

Route::any('test/{aux?}', 'TestController@test');
Route::any('test2/{aux?}', 'TestController@test2');
Route::any('test3/{aux?}', 'TestController@test3');
Route::any('test4/{aux?}', 'TestController@test4');
Route::any('test5/{aux?}', 'TestController@test5');
Route::any('test6/{aux?}', 'TestController@test6');
Route::any('test7/{aux?}', 'TestController@test7');
Route::any('test8/{aux?}', 'TestController@test8');
Route::any('test9/{aux?}', 'TestController@test9');
Route::any('test10/{aux?}', 'TestController@test10');

Route::any('pages/{subs?}', ['uses' => 'PageController@index'])->where(['subs' => '.*']);

app/Models/Cie10.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class Cie10 extends Model
{
	use CrudTrait;

     /*
	|--------------------------------------------------------------------------
	| GLOBAL VARIABLES
	|--------------------------------------------------------------------------
	*/

	protected $table = 'cie10';
	protected $primaryKey = 'id';
	// public $timestamps = false;
	// protected $guarded = ['id'];
	protected $fillable = ['codigo','descripcion'];
	// protected $hidden = [];
    // protected $dates = [];

	/*
	|--------------------------------------------------------------------------
	| FUNCTIONS
	|--------------------------------------------------------------------------
	*/
	public function getTituloAttribute($value)
	{
		return $this->codigo . "-" . $this->descripcion;
	}
	/*
	|--------------------------------------------------------------------------
	| RELATIONS
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| SCOPES
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| ACCESORS
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| MUTATORS
	|--------------------------------------------------------------------------
	*/
}

resources/views/clinica/partials/ficha-historia-clinica.blade.php
    <div class="box box-solid box-primary hover">
        <div class="box-header">
            <h5>Historia Clínica de <a href="{{url('admin/ver-paciente/'. $historia->paciente_id)}}"> <span>{{$historia->paciente->full_name}}</a></span></h5>

            <div class="box-tools pull-right">
              <b><i class="fa fa-clock-o"></i> </b> {{\App\Funciones::transdate($historia->fecha , 'l j \d\e F \d\e Y')}}
              <button class="btn btn-xs btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          </div>            
      </div>
      <div class="box-body">

        <h2 class="">Anamnesis</h2>
        <hr>
        <div class="col-md-12">
            <b class="text-uppercase text-primary">Motivo de la Consulta:</b> <p class="text-justify"> {{$historia->motivo_de_consulta}} </p>
        </div>

        <div class="col-md-12">
            <b class="text-uppercase text-primary">Enfermedad Actual:</b> <p class="text-justify">{{$historia->enfermedad_actual}}</p>
        </div>

        <div class="col-md-12">
            <b class="text-uppercase text-primary">Revision por Sistema:</b> <p class="text-justify">{{$historia->revision_por_sistema}}</p>
        </div>

        <h2 class="">Antecedentes</h2>
        <hr>

        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Patologicos:</b> <p class="text-justify">{{$historia->patologicos}}</p>
        </div>       

        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Quirurjicos:</b> <p class="text-justify">{{$historia->quirurjicos}}</p>
        </div>    

        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Farmacologicos:</b> <p class="text-justify">{{$historia->farmacologicos}}</p>
        </div>

        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Farmacologicos:</b> <p class="text-justify">{{$historia->farmacologicos}}</p>
        </div>

        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Traumaticos:</b> <p class="text-justify">{{$historia->traumaticos}}</p>
        </div>


        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Inmunologicos:</b> <p class="text-justify">{{$historia->inmunologicos}}</p>
        </div>


        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Hospitalarios:</b> <p class="text-justify">{{$historia->hospitalarios}}</p>
        </div>


        <div class="col-md-6">
            <b class="text-uppercase text-primary">Antecedentes Toxico Alergicos:</b> <p class="text-justify">{{$historia->toxico_alergicos}}</p>
        </div>


        <h2 class="">Examen Físico</h2>
        <hr>

        <div class="col-md-2">
            <b class="text-uppercase text-primary">Frecuencia Cardiaca:</b> <p class="text-justify">{{$historia->frecuencia_cardiaca}}</p>
        </div>       

        <div class="col-md-2">
            <b class="text-uppercase text-primary">Frecuencia Respirtoria:</b> <p class="text-justify">{{$historia->frecuencia_respiratoria}}</p>
        </div>    

        <div class="col-md-2">
            <b class="text-uppercase text-primary">Tensión Arterial:</b> <p class="text-justify">{{$historia->tension_arterial}}</p>
        </div>

        <div class="col-md-2">
            <b class="text-uppercase text-primary">Temperatura:</b> <p class="text-justify">{{$historia->temperatura}}</p>
        </div>

        <div class="col-md-2">
            <b class="text-uppercase text-primary">Peso:</b> <p class="text-justify">{{$historia->peso}}</p>
        </div>


        <div class="col-md-2">
            <b class="text-uppercase text-primary">Talla:</b> <p class="text-justify">{{$historia->talla}}</p>
        </div>


        <div class="col-md-12 text-center">
            <b class="text-uppercase text-primary">Aspecto General:</b> <p class="text-justify">{{$historia->aspecto_general}}</p>
        </div>

           <br> <hr>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Cabeza/Cuello:</b> <p class="text-justify">{{$historia->cabeza_cuello}}</p>
        </div>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Orl</b>
            <p class="text-justify">{{$historia->orl}}</p>
        </div>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Cardio/Pulmonar</b>
            <p class="text-justify">{{$historia->cardio_pulmonar}}</p>
        </div>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Abdomen</b>
            <p class="text-justify">{{$historia->abdomen}}</p>
        </div>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Extremidades</b>
            <p class="text-justify">{{$historia->extremidades}}</p>
        </div>
        <div class="col-md-4">
            <b class="text-uppercase text-primary">Piel</b>
            <p class="text-justify">{{$historia->piel}}</p>
        </div>
       <div class="col-md-12">
            <b class="text-uppercase text-primary">Neurologico</b>
            <p class="text-justify">{{$historia->neurologico}}</p>
        </div>

        <div class="col-md-12">
            <b class="text-uppercase text-primary">Notas:</b> <p class="text-justify">{{$historia->notas}}</p>
        </div>
        
        <div class="col-md-12">
            <h2>Resultados</h2>
        </div>
        <hr>
        <div class="col-md-12">
            <b class="text-uppercase text-primary">Analisis:</b> <p class="text-justify">{{$historia->analisis}}</p>
        </div>

        <div class="col-md-12">
            <b class="text-uppercase text-primary">Diagnostico CIE10:</b> <p class="text-justify">@if($historia->cie10){{$historia->cie10->titulo}}@endif</p>
        </div>
    </div>




    <div class="box-footer ">
        <p class="pull-left">
            <b>Ingreso:</b> <span>{{$historia->ingreso}}</span> |
            <b>Egreso:</b> <span>{{$historia->egreso}}</span>
        </p>
        <p class="pull-right">
            <b>Médico:</b>  <span>{{$historia->medico->nombre}}</span>
        </p>
    </div>
</div>

resources/views/clinica/partials/tabla-documentos.blade.php
  <div class="box box-default">
    <div class="box-header">
       Documentos
      <div class="box-tools pull-right">
        <button class="btn  btn-xs btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body">
      <ul class="nav nav-stacked">
      @forelse ($documentos as $doc)
        <li><a href="{{ $doc->url() }}">{{$doc->nombre}} <span class="pull-right badge bg-blue"><i class="fa fa-download"></i></span></a></li>
      @empty
         <li><a>No Hay Documentos</a></li>
      @endforelse
      </ul>
      
    </div>
  </div>

resources/views/clinica/partials/tabla-historias-clinicas.blade.php
    <div class="box box-default hover">
        <div class="box-header">
            <h5 class="text-primary">Historias Clínicas</h5>
            <div class="box-tools pull-right">
              <button class="btn btn-xs btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Fecha</th>
                            <th>Resultado - CIE10</th>
                            <th>Analisis</th>
                            <th>Médico</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php $i=1 ?>
                    @forelse ($historias as $hist)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{\App\Funciones::transdate($hist->fecha, 'l j \d\e F \d\e Y')}}</td>
                            <td>@if($hist->cie10){{$hist->cie10->titulo}}@endif</td>
                            <td>{{str_limit($hist->analisis)}}</td>
                            <td>@if($hist->medico){{$hist->medico->nombre}}@endif</td>
                            <td><a class="btn btn-sm" href="{{url('admin/ver-historia-clinica/' . $hist->id)}}">Ver</a></td>
                        </tr>
                    @empty
                    <tr>
                        Este paciente no tiene ninguna historia clinica
                    </tr>
                    @endforelse

                    </tbody>
                </table>
            <a class="btn btn-primary" href="{{url('admin/historias_clinicas/create?paciente_id='. $paciente->id)}}">Agregar Historia Clínica</a>
            </div>
        </div>
    </div>

resources/views/clinica/partials/timeline-recomendaciones.blade.php
    <div class="well">
       <ul class="timeline">
          <!-- timeline time label -->
          <li class="time-label">
            <span class="bg-red">
              Recomendaciones
            </span>
          </li>
          @foreach ($recomendaciones as $recomendacion)
          <li>
            <i class="fa fa-comments bg-yellow"></i>

            <div class="timeline-item">
              <span class="time"><i class="fa fa-clock-o"></i>{{\App\Funciones::transdate($recomendacion->created_at, 'd/m/y h:m:i A')}}</span>

              <h3 class="timeline-header">{{$recomendacion->titulo}}</h3>

              <div class="timeline-body">
                {{$recomendacion->descripcion}}
              </div>
              <div class="timeline-footer">
                <div style="height: 40px; width: 40px;" class="pull-left">
                  <img src="{{$recomendacion->user->imagen()}}" class="img-responsive img-circle" alt="">
                </div>
                <span class="text-primary">
                  {{$recomendacion->user->nombre}}
                </span>
              </div>
            </div>
          </li>
          @endforeach
          <li>
             <div class="timeline-item">
                <div class="timeline-body">
                   <a class="btn btn-primary" href="{{url('admin/recomendaciones/create?caso_id='. $caso->id)}}"> <i class="fa fa-calendar-plus-o"></i> Agregar Recomendación</a>
                </div>
             </div>
          </li>
      </ul>
    </div>